import { MarketInstrument } from "./market.types";

export const DEFAULT_TICKER_REFRESH_INTERVAL_MS = 30000;

export const INITIAL_MARKET_DATA: MarketInstrument[] = [
  {
    id: "gold",
    symbol: "GOLD",
    displayName: "Gold Spot",
    price: "3,345.28",
    rawPrice: 3345.28,
    change: "+17.30",
    changePercent: "+0.52%",
    direction: "up",
    icon: "🟡",
    displayOrder: 1,
    enabled: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "silver",
    symbol: "SILVER",
    displayName: "Silver Spot",
    price: "38.12",
    rawPrice: 38.12,
    change: "-0.05",
    changePercent: "-0.14%",
    direction: "down",
    icon: "⚪",
    displayOrder: 2,
    enabled: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "eurusd",
    symbol: "EUR/USD",
    displayName: "Euro / US Dollar",
    price: "1.1734",
    rawPrice: 1.1734,
    change: "+0.0009",
    changePercent: "+0.08%",
    direction: "up",
    displayOrder: 3,
    enabled: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "gbpusd",
    symbol: "GBP/USD",
    displayName: "British Pound / US Dollar",
    price: "1.3528",
    rawPrice: 1.3528,
    change: "-0.0030",
    changePercent: "-0.22%",
    direction: "down",
    displayOrder: 4,
    enabled: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "usdjpy",
    symbol: "USD/JPY",
    displayName: "US Dollar / Japanese Yen",
    price: "148.44",
    rawPrice: 148.44,
    change: "+0.16",
    changePercent: "+0.11%",
    direction: "up",
    displayOrder: 5,
    enabled: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "btc",
    symbol: "BTC",
    displayName: "Bitcoin / USD",
    price: "117,245.00",
    rawPrice: 117245.0,
    change: "+1,640.00",
    changePercent: "+1.42%",
    direction: "up",
    displayOrder: 6,
    enabled: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "eth",
    symbol: "ETH",
    displayName: "Ethereum / USD",
    price: "3,842.50",
    rawPrice: 3842.5,
    change: "+78.30",
    changePercent: "+2.08%",
    direction: "up",
    displayOrder: 7,
    enabled: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "nifty",
    symbol: "NIFTY 50",
    displayName: "NSE Nifty 50 Index",
    price: "24,920.80",
    rawPrice: 24920.8,
    change: "+143.50",
    changePercent: "+0.58%",
    direction: "up",
    displayOrder: 8,
    enabled: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "banknifty",
    symbol: "BANK NIFTY",
    displayName: "NSE Bank Nifty Index",
    price: "57,110.25",
    rawPrice: 57110.25,
    change: "-138.40",
    changePercent: "-0.24%",
    direction: "down",
    displayOrder: 9,
    enabled: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "nasdaq",
    symbol: "NASDAQ",
    displayName: "Nasdaq 100 Index",
    price: "23,614.40",
    rawPrice: 23614.4,
    change: "+72.80",
    changePercent: "+0.31%",
    direction: "up",
    displayOrder: 10,
    enabled: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "sp500",
    symbol: "S&P 500",
    displayName: "S&P 500 Index",
    price: "6,460.10",
    rawPrice: 6460.1,
    change: "+11.60",
    changePercent: "+0.18%",
    direction: "up",
    displayOrder: 11,
    enabled: true,
    lastUpdated: new Date().toISOString(),
  },
];
